//YWROBOT
//Compatible with the Arduino IDE 1.0
//Library version:1.1
#include <Wire.h> 
#include <LiquidCrystal_I2C.h>

int delaytime = 200;


LiquidCrystal_I2C lcd(0x27,20,4);  // set the LCD address to 0x27 for a 16 chars and 2 line display

void setup()
{
  lcd.init();                      // initialize the lcd 
  lcd.init();
  
  lcd.backlight();
}


void loop()
{lcd.clear();
lcd.clear();
lcd.setCursor(0,0);
  lcd.print("               3");
  lcd.setCursor(0,1);
  lcd.print("                ");
  delay(delaytime);
lcd.clear();
lcd.setCursor(0,0);
  lcd.print("              3A");
  lcd.setCursor(0,1);
  lcd.print("                ");
  delay(delaytime);
lcd.clear();
lcd.setCursor(0,0);
  lcd.print("             3A ");
  lcd.setCursor(0,1);
  lcd.print("               K");
  delay(delaytime);
lcd.clear();
lcd.setCursor(0,0);
  lcd.print("            3A M");
  lcd.setCursor(0,1);
  lcd.print("              KE");
  delay(delaytime);
lcd.clear();
lcd.setCursor(0,0);
  lcd.print("           3A ME");
  lcd.setCursor(0,1);
  lcd.print("             KEL");
  delay(delaytime);
lcd.clear();
lcd.setCursor(0,0);
  lcd.print("          3A MEK");
  lcd.setCursor(0,1);
  lcd.print("            KELO");
  delay(delaytime);
lcd.clear();
lcd.setCursor(0,0);
  lcd.print("         3A MEKA");
  lcd.setCursor(0,1);
  lcd.print("           KELOM");
  delay(delaytime);
lcd.clear();
lcd.setCursor(0,0);
  lcd.print("        3A MEKAT");
  lcd.setCursor(0,1);
  lcd.print("          KELOMP");
  delay(delaytime);
lcd.clear();
lcd.setCursor(0,0);
  lcd.print("       3A MEKATR");
  lcd.setCursor(0,1);
  lcd.print("         KELOMPO");
  delay(delaytime);
lcd.clear();
lcd.setCursor(0,0);
  lcd.print("      3A MEKATRO");
  lcd.setCursor(0,1);
  lcd.print("        KELOMPOK");
  delay(delaytime);
lcd.clear();
lcd.setCursor(0,0);
  lcd.print("     3A MEKATRON");
  lcd.setCursor(0,1);
  lcd.print("       KELOMPOK ");
  delay(delaytime);
lcd.clear();
lcd.setCursor(0,0);
  lcd.print("    3A MEKATRONI");
  lcd.setCursor(0,1);
  lcd.print("      KELOMPOK 2");
  delay(delaytime);
  lcd.clear();
lcd.setCursor(0,0);
  lcd.print("   3A MEKATRONIK");
  lcd.setCursor(0,1);
  lcd.print("     KELOMPOK 2");
  delay(delaytime);
  lcd.clear();
  lcd.setCursor(0,0);
  lcd.print("  3A MEKATRONIKA");
  lcd.setCursor(0,1);
  lcd.print("    KELOMPOK 2");
  delay(delaytime);
    lcd.clear();
  lcd.setCursor(0,0);
  lcd.print(" 3A MEKATRONIKA");
  lcd.setCursor(0,1);
  lcd.print("   KELOMPOK 2");
  delay(delaytime);
  lcd.clear();
  lcd.setCursor(0,0);
  lcd.print("3A MEKATRONIKA");
  lcd.setCursor(0,1);
  lcd.print("  KELOMPOK 2");
  delay(delaytime);
  lcd.clear();
  lcd.setCursor(0,0);
  lcd.print("A MEKATRONIKA");
  lcd.setCursor(0,1);
  lcd.print(" KELOMPOK 2");
  delay(delaytime);
    lcd.clear();
  lcd.setCursor(0,0);
  lcd.print(" MEKATRONIKA");
  lcd.setCursor(0,1);
  lcd.print("KELOMPOK 2");
  delay(delaytime);
  lcd.clear();
  lcd.setCursor(0,0);
  lcd.print("MEKATRONIKA     M");
  lcd.setCursor(0,1);
  lcd.print("ELOMPOK 2");
  delay(delaytime);
    lcd.clear();
  lcd.setCursor(0,0);
  lcd.print("EKATRONIKA     ME");
  lcd.setCursor(0,1);
  lcd.print("LOMPOK 2");
  delay(delaytime);
  lcd.clear();
  lcd.setCursor(0,0);
  lcd.print("KATRONIKA    MEK");
  lcd.setCursor(0,1);
  lcd.print("OMPOK 2        C");
  delay(delaytime);
  lcd.clear();
  lcd.setCursor(0,0);
  lcd.print("ATRONIKA    MEKA");
  lcd.setCursor(0,1);
  lcd.print("MPOK 2        CO");
  delay(delaytime);
  lcd.clear();
  lcd.setCursor(0,0);
  lcd.print("TRONIKA    MEKAD");
  lcd.setCursor(0,1);
  lcd.print("POK 2        CON");
  delay(delaytime);
  lcd.clear();
  lcd.setCursor(0,0);
  lcd.print("RONIKA    MEKADA");
  lcd.setCursor(0,1);
  lcd.print("OK 2        CONV");
  delay(delaytime);
  lcd.clear();
  lcd.setCursor(0,0);
  lcd.print("ONIKA    MEKADAY");
  lcd.setCursor(0,1);
  lcd.print("K 2        CONVE");
  delay(delaytime);
  lcd.clear();
  lcd.setCursor(0,0);
  lcd.print("NIKA    MEKADAY ");
  lcd.setCursor(0,1);
  lcd.print(" 2        CONVEY");
  delay(delaytime);
  lcd.clear();
  lcd.setCursor(0,0);
  lcd.print("IKA    MEKADAY 2");
  lcd.setCursor(0,1);
  lcd.print("2        CONVEYO");
  delay(delaytime);
  lcd.clear();
  lcd.setCursor(0,0);
  lcd.print("KA    MEKADAY 20");
  lcd.setCursor(0,1);
  lcd.print("        CONVEYOR");
  delay(delaytime);
  lcd.clear();
  lcd.setCursor(0,0);
  lcd.print("A    MEKADAY 202");
  lcd.setCursor(0,1);
  lcd.print("       CONVEYOR ");
  delay(delaytime);
  lcd.clear();
  lcd.setCursor(0,0);
  lcd.print("    MEKADAY 2021");
  lcd.setCursor(0,1);
  lcd.print("      CONVEYOR  ");
  delay(delaytime);
  lcd.clear();
  lcd.setCursor(0,0);
  lcd.print("   MEKADAY 2021 ");
  lcd.setCursor(0,1);
  lcd.print("     CONVEYOR   ");
  delay(delaytime);
  lcd.clear();
  lcd.setCursor(0,0);
  lcd.print("  MEKADAY 2021 ");
  lcd.setCursor(0,1);
  lcd.print("    CONVEYOR   ");
  delay(delaytime);
  lcd.clear();
  delay(1000);
  lcd.setCursor(0,0);
  lcd.print("  MEKADAY 2021 ");
  lcd.setCursor(0,1);
  lcd.print("    CONVEYOR   ");
  delay(1000);
  lcd.clear();
  delay(1000);
  lcd.setCursor(0,0);
  lcd.print("  MEKADAY 2021 ");
  lcd.setCursor(0,1);
  lcd.print("    CONVEYOR   ");
  delay(3000);

  
}